### ISSUE TITLE
Always "Invalid Flightmode"

### ISSUE THREAD

**Issue by Seeelefant** [athertop/MavLink_FrSkySPort#27]
All values are correct, but only for flight mode I alway get "Invalid Flightmode". Looking at the (right instance of) the FUEL value I get
 Stabilized: 458752
 PosHold:  196608
 AltHold:   131072 
 Hold:        50593792
 Land:        100925440 
 Mission:    67371008
Seems that something happened......

**Comment by athertop** [comment]
You are possibly looking at the wrong sensor for Flight mode - Flight mode is reported on the Fuel sensor derived from Sensor 0600 instance 8 - the values you are showing above appear to be those on the instance 9 sensor which should have been renamed tom MSG. Also note, that the naming of sensor is case sensitive so "FUEL" is not the same as "Fuel"

**Comment by Seeelefant** [comment]
Unfortunately yes, however I am using the PX$/PixRacer stack.

 

Von: athertop [mailto:notifications@github.com] 
Gesendet: Sonntag, 29. Juli 2018 17:19
An: athertop/MavLink_FrSkySPort
Cc: Seeelefant; Author
Betreff: Re: [athertop/MavLink_FrSkySPort] Always "Invalid Flightmode" (#27)

 

You sure you have Copter/Plane selected correctly in config screen to match your Ardupilot firmware?

**Comment by athertop** [comment]
Sorry, this project only supports Ardupilot Plane/Copter. Can I please make a recommendation that you check out the project https://github.com/yaapu/FrskyTelemetryScript - it is a huge advancement over this project - it however only supports FrSky passthrough protocol (which is not supported by the PX4 stack), so in order to use it with the PX4 stack, you can use the teensy converter from this project: https://github.com/zs6buj/MavlinkToPassthru
These two projects combined make for an excellent telemetry solution - I now use this combo myself on my LRS based planes. For my FrSky based planes I use just the LUA script with passthrough protocol produced from telemetry port of Aerdupilot FC.
